{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.0.0.jar",
          "url": "stringblur-1.0.0.jar",
          "size": 52288,
          "sha512": "91ad3f6acc80a1ae50e12de1cb2782fee533ba1315ea1420bca815a193f22190b076f4973543e9325718daeeddca742a2f27c330170178e042a0d7d808930678",
          "sha256": "13b8c3d5085b96279a4923e4ebd098f616a807dcd4297dc86eeb858616b1fcd4",
          "sha1": "909b9a437a632884d3da07e24344f64bd1d5e646",
          "md5": "7bdb98fd351db1843eb9754af7ac6655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.0.0.jar",
          "url": "stringblur-1.0.0.jar",
          "size": 52288,
          "sha512": "91ad3f6acc80a1ae50e12de1cb2782fee533ba1315ea1420bca815a193f22190b076f4973543e9325718daeeddca742a2f27c330170178e042a0d7d808930678",
          "sha256": "13b8c3d5085b96279a4923e4ebd098f616a807dcd4297dc86eeb858616b1fcd4",
          "sha1": "909b9a437a632884d3da07e24344f64bd1d5e646",
          "md5": "7bdb98fd351db1843eb9754af7ac6655"
        }
      ]
    }
  ]
}
