{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.string.plugin",
    "module": "stringblur",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.0.0.jar",
          "url": "stringblur-1.0.0.jar",
          "size": 54255,
          "sha512": "2340dd5d77631456c88b37a3e3049d98ab70f3f67d544f877fd57e2a675e9e505502b14db5d1ef469db8573536d302a0066521f312572ca3fd8b1dbfc7d7ea90",
          "sha256": "db4dc0dd2b4af83acd072778af653620cd67c9b21de14909457b1ec879e3fb60",
          "sha1": "a60a0deee54279bb629e81b5070de790a04540bd",
          "md5": "7fa8c6c0147480e474529f84536f5e12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "stringblur-1.0.0.jar",
          "url": "stringblur-1.0.0.jar",
          "size": 54255,
          "sha512": "2340dd5d77631456c88b37a3e3049d98ab70f3f67d544f877fd57e2a675e9e505502b14db5d1ef469db8573536d302a0066521f312572ca3fd8b1dbfc7d7ea90",
          "sha256": "db4dc0dd2b4af83acd072778af653620cd67c9b21de14909457b1ec879e3fb60",
          "sha1": "a60a0deee54279bb629e81b5070de790a04540bd",
          "md5": "7fa8c6c0147480e474529f84536f5e12"
        }
      ]
    }
  ]
}
